name: appimagepool
description: A simple, modern AppImageHub Client made for linux using flutter.

version: 5.1.0
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  adwaita:
  cached_network_image: ^3.1.0
  carousel_slider: ^4.0.0
  desktop_notifications: ^0.6.3
  dio: ^5.0.1
  flutter_localizations: 
    sdk: flutter
  file_picker: ^5.2.5
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.6
  gap: ^3.0.1
  hooks_riverpod: ^2.0.0-dev.9
  intl: ^0.18.1
  libadwaita: ^2.0.0
  libadwaita_searchbar: ^0.5.0+1
  libadwaita_window_manager:
  lucide_icons: ^0.115.0
  package_info_plus: ^4.0.0
  path_provider: ^2.0.5
  shared_preferences: ^2.0.8
  simple_html_css: ^4.0.0
  sticky_headers: ^0.3.0+2
  url_launcher: ^6.0.12
  window_manager: ^0.3.1
  file: ^6.1.4
  flutter_hooks: ^0.20.3
  path: ^1.8.3
  palette_generator: ^0.3.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  generate: true
