name: FlutterAppImageCI

on:
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@master
        with:
          channel: stable
          
      - name: Get Packages
        run: >
              flutter pub get;
              flutter config --enable-linux-desktop;
              sudo apt-get update;
              sudo apt-get install clang cmake ninja-build pkg-config libgtk-3-dev;
              flutter doctor -v;

      - name: Download required resources to Generate AppImage
        uses: wei/wget@v1
        with:
          args: -O appimagetool-x86_64.AppImage https://github.com/AppImage/AppImageKit/releases/download/12/appimagetool-x86_64.AppImage
        
      - name: Build Linux App
        run: > 
              flutter build linux;
              cp -r build/linux/release/bundle/* AppImageBrowser.AppDir;
              sudo chmod +x appimagetool-x86_64.AppImage;

      - name: Generate AppImage
        run: ARCH=x86_64 ./appimagetool-x86_64.AppImage AppImageBrowser.AppDir/ appimagebrowser.AppImage

      - name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: appimagebrowser.AppImage
          tag: ${{ github.ref }}
          overwrite: true

#      - name: Upload to Artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: appimage-release
#          path: ./appimagebrowser.AppImage

